### ISSUE TITLE
Cider 2 update 2.5.0 restructures api endpoints

### ISSUE THREAD

**Issue by NPC-112** [ThatGravyBoat/Jukebox#2]
See https://github.com/ciderapp/Cider-2/blob/main/docs/Cider%202.5.0%20Preview%20API.md
for the details. 

link for previous API: https://cider.sh/docs/client/rpc

**Comment by LarveyOfficial** [comment]
+1 on this.

Port has changed from 10769 to 10767, and they now use Sockets.io

**Comment by ThatGravyBoat** [comment]
I've finally had time to look into this and ran into some issues with getting events from the API I made a report so until I can get that resolved this will have to be delayed https://github.com/ciderapp/Cider-2/issues/828

**Comment by ThatGravyBoat** [comment]
This is done in https://github.com/ThatGravyBoat/Jukebox/commit/6f517485da132618a734bac7eb090058ce5f1d76, Craftify update will soon follow sometime this week or weekend
